version: "3.9"
networks:
  default:
    name: img-2-data
services:
  app:
    container_name: img-2-data-app
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      cd app
      npm install
      npm run build
    working_dir: /Img2Data
    volumes:
      - ./:/Img2Data