name: Deploy to NPM
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker compose up

      - name: Create 'dist' folder
        run: sh setup_dist.sh

      - name: Upload 'dist' folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/**/*

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}