name: Deploy to NPM
on:
  push:
    branches:
      - master
jobs:
  upload-dist-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Upload 'dist' folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/**/*