name: Deploy to NPM
on:
  push:
    branches:
      - master
jobs:
  deploy-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker compose up

      - name: Create 'dist' folder
        run: |
          mkdir -p dist
          cd app
          cp index.html ../dist/
          cp -r node_modules ../dist/

      - name: Upload 'dist' folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/**/*
